### ISSUE TITLE
Cabal build fails with random-1.2.0 (2)

### ISSUE THREAD

**Issue by whosystem** [cardano-foundation/cardano-wallet#2579] opened 2021-03-25 04:59 UTC
cabal build Cardano.Wallet.DB.Sqlite.Types
# Context
`
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - cardano-wallet-core-2021.3.4 (lib) (first run)
Preprocessing library for cardano-wallet-core-2021.3.4..
Building library for cardano-wallet-core-2021.3.4..
[51 of 83] Compiling Cardano.Wallet.DB.Sqlite.Types ( src/Cardano/Wallet/DB/Sqlite/Types.hs, /media/sf_cardano/src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.4/cardano-wallet-core-2021.3.4/build/Cardano/Wallet/DB/Sqlite/Types.o, /media/sf_cardano/src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.4/cardano-wallet-core-2021.3.4/build/Cardano/Wallet/DB/Sqlite/Types.dyn_o )

src/Cardano/Wallet/DB/Sqlite/Types.hs:533:24: error:
    • No instance for (Read StdGen)
        arising from a use of ‘fromPersistValueRead’
    • In the expression: fromPersistValueRead
      In an equation for ‘fromPersistValue’:
          fromPersistValue = fromPersistValueRead
      In the instance declaration for ‘PersistField StdGen’
    |
533 |     fromPersistValue = fromPersistValueRead
    |                        ^^^^^^^^^^^^^^^^^^^^`

=================commands executed to install sqlite3==================
 1291  sudo apt install sqlite3
 1292  sudo apt install sqlite3-dev
 1293  sudo apt install sqlite-dev
 1294  sudo apt-cache search sqlite
 1295  sudo apt install sqlite3
 1296  sudo apt install libsqlite3-dev
 1314  sudo apt install 'libsqlite*-dev'
================below the existing sqlite files===============================
cardano@ubscardano:~/src/cardano-wallet$ !find 
find /usr -name '*sqlite3*' 
/usr/bin/sqlite3
/usr/include/sqlite3ext.h
/usr/include/sqlite3.h
/usr/lib/python2.7/sqlite3
/usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
/usr/lib/firefox/libmozsqlite3.so
/usr/lib/thunderbird/libmozsqlite3.so
/usr/lib/python3.8/sqlite3
/usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so
/usr/lib/ocaml/stublibs/dllsqlite3_stubs.so
/usr/lib/ocaml/sqlite3
/usr/lib/ocaml/sqlite3/sqlite3.cmxs
/usr/lib/ocaml/sqlite3/sqlite3.mli
/usr/lib/ocaml/sqlite3/sqlite3.ml
/usr/lib/ocaml/sqlite3/sqlite3.cmx
/usr/lib/ocaml/sqlite3/sqlite3.cmti
/usr/lib/ocaml/sqlite3/sqlite3.cmxa
/usr/lib/ocaml/sqlite3/sqlite3.cmt
/usr/lib/ocaml/sqlite3/sqlite3.cma
/usr/lib/ocaml/sqlite3/sqlite3.cmi
/usr/lib/ocaml/sqlite3/libsqlite3_stubs.a
/usr/lib/ocaml/sqlite3/sqlite3.a
/usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc
/usr/lib/x86_64-linux-gnu/libsqlite3.la
/usr/lib/x86_64-linux-gnu/libsqlite3.a
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0
/usr/lib/x86_64-linux-gnu/apr-util-1/apr_dbd_sqlite3-1.so
/usr/lib/x86_64-linux-gnu/apr-util-1/apr_dbd_sqlite3.so
/usr/lib/x86_64-linux-gnu/libsqlite3.so
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
/usr/share/man/man1/sqlite3.1.gz
/usr/share/icons/Humanity/mimes/24/application-x-sqlite3.svg
/usr/share/icons/Humanity/mimes/48/application-x-sqlite3.svg
/usr/share/icons/Humanity/mimes/22/application-x-sqlite3.svg
/usr/share/icons/Yaru/32x32/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/24x24/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/32x32@2x/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/256x256/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/16x16@2x/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/256x256@2x/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/48x48@2x/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/16x16/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/48x48/mimetypes/application-x-sqlite3.png
/usr/share/icons/Yaru/24x24@2x/mimetypes/application-x-sqlite3.png
/usr/share/bash-completion/completions/sqlite3
/usr/share/mime/application/x-kexiproject-sqlite3.xml
/usr/share/mime/application/vnd.sqlite3.xml
/usr/share/doc/libaprutil1-dbd-sqlite3
/usr/share/doc/libsqlite3-ocaml
/usr/share/doc/libsqlite3-0
/usr/share/doc/sqlite3
/usr/share/doc/libdbd-sqlite3-perl
/usr/share/doc/libsqlite3-dev
/usr/share/doc/libsqlite3-ocaml-dev

=========================space on system=========================
cardano@ubscardano:~/src/cardano-wallet$ df -h 
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  1.5M  1.6G   1% /run
/dev/sda2       492G   58G  409G  13% /
tmpfs           7.9G  592M  7.3G   8% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop1      157M  157M     0 100% /snap/code/59
/dev/loop3       33M   33M     0 100% /snap/snapd/11107
/dev/loop2      100M  100M     0 100% /snap/core/10908
/dev/loop0      156M  156M     0 100% /snap/code/57
/dev/loop4       55M   55M     0 100% /snap/core18/1880
/dev/loop5      100M  100M     0 100% /snap/core/10859
/dev/loop6       70M   70M     0 100% /snap/lxd/19188
/dev/loop8       56M   56M     0 100% /snap/core18/1988
/dev/loop7      291M  291M     0 100% /snap/kde-frameworks-5-qt-5-14-core18/4
/dev/loop9       16M   16M     0 100% /snap/umbrello/41
/dev/loop10      71M   71M     0 100% /snap/lxd/19647
/dev/loop11     240M  240M     0 100% /snap/zoom-client/136
/dev/loop12      33M   33M     0 100% /snap/snapd/11402
/dev/loop13     240M  240M     0 100% /snap/zoom-client/134
cardano         1.9T  597G  1.3T  33% /media/sf_cardano
tmpfs           1.6G   68K  1.6G   1% /run/user/1001
/dev/sdb1       3.8G  1.1G  2.8G  27% /media/cardano/VB-BLUE
## Essential Information
-**Version**:      latest
-**Platform**:     Linux
-**Installation**: Built from source from GitHub release page
-**Network**:      n/a
`cardano@ubscardano:~/src/cardano-wallet$ lsb_release -a`
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 20.04.2 LTS`
`Release:	20.04`
`Codename:	focal`
`cardano@ubscardano:~/src/cardano-wallet$ uname -a`
`Linux ubscardano 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

# Steps to Reproduce
cabal configure 
cabal build Cardano.Wallet.DB.Sqlite.Types

as above 
## Actual behavior

---

# Jira ticket

ADP-961

**Comment by Mercurial** [comment] 2021-06-01 14:36
I'm also experiencing this issue when compiling under `Ubuntu 20.04` can anyone advice how to get past this? I've tried both ghc `8.10.2` and `8.10.4`

```
src/Cardano/Wallet/DB/Sqlite/Types.hs:554:24: error:
    • No instance for (Read StdGen)
        arising from a use of ‘fromPersistValueRead’
    • In the expression: fromPersistValueRead
      In an equation for ‘fromPersistValue’:
          fromPersistValue = fromPersistValueRead
      In the instance declaration for ‘PersistField StdGen’
    |
554 |     fromPersistValue = fromPersistValueRead
    |                        ^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-wallet-core-2021.5.26 (which is required by
exe:local-cluster from cardano-wallet-2021.5.26, test:integration from
cardano-wallet-2021.5.26 and others).
```

**Comment by rvl** [comment] 2021-06-02 03:11
Hello @whosystem, @Mercurial, thanks for reporting. You can work around this either by using the stack build tool, or adding a Cabal option like this:
```console
$ cabal configure --constraint="random<1.2"
$ cabal build all
```

**Comment by Mercurial** [comment] 2021-06-02 03:12
> Hello @whosystem, @Mercurial, thanks for reporting. You can work around this either by using the stack build tool, or adding a Cabal option like this:
> 
> ```console
> 
> $ cabal configure --constraint="random<1.2"
> 
> $ cabal build all
> 
> ```
> 
> 

Thank you very much!

**Comment by rvl** [comment] 2021-06-02 03:38
I'll set this as a duplicate of #2685.

**Closed as completed by rvl** 2021-06-02 03:38 UTC
Labels: Bug
