### ISSUE TITLE
Unable to import arbitrarily created credentials 

### ISSUE THREAD

**Issue by aidik** [cardano-foundation/cardano-wallet#1244] opened 2020-01-02 18:22 UTC
# Context
 Operating a stake pool with arbitrarily created credentials `jcli key generate --type ed25519` I'm unable to import those credentials, work with the wallet and see staking rewards. 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: f3576be15de4976e753dea212aa5d44c334bd204) |
| Platform     | Linux          |
| Installation | From Github Release         |

**Comment by KtorZ** [comment] 2020-01-02 19:47
Hi, what do you mean with "import those credentials" :thinking: ?

`cardano-wallet` implements various flavor of hierarchical deterministic wallets. Said differently, it creates a tree from a root where nodes and leaves are private keys that can be derived from their parent node. Ultimately, only a single key (the root node) is needed to recover the whole tree; this key is typically encoded as a mnemonic sentence (e.g. `abandon squirrel ...` etc ..)  

Now, `cardano-wallet` offers an API where entry points to create wallets require users to provide such mnemonic sentence. It does not support tracking funds from a raw private (or public) key _yet_.

**Comment by aidik** [comment] 2020-01-03 13:56
@KtorZ Hi, thank you for your prompt answer. 

> Hi, what do you mean with "import those credentials" 🤔 ?

Basically to import the root key without mnemonic encode but directly from the `ed25519_sk...` key.

> It does not support tracking funds from a raw private (or public) key _yet_.

What would you suggest as a solution in the meantime? Is it possible to re-encode the key into a mnemonic sentence?

**Comment by KtorZ** [comment] 2020-01-03 14:16
Well, the issue is subtle here. A key is, in essence, nothing more than a bunch of scrambled bytes. Now, the question is _how you look at these bytes_ and how you consider them. There's nothing really different between a root private key from an HD (HD as in **H**ierarchical **D**eterministic) tree and a address private key except a certain cryptographic relationship that makes it possible to recover the address private key from the root key (but it's not a symmetrical relationship, one cannot recover the parent key from a child key!) 

`cardano-wallet` is a piece of software that can be instrumented to keep track of funds designated by UTxO address public keys assuming a very specific HD structure. This means that, if there are funds "located" at your public key above then, if you want it tracked by `cardano-wallet`, you need to have the correspond parent key, which you probably don't have. 

There are future plans for the cardano eco-system to allow keeping track of other types of wallet that aren't necessarily HD wallets but, we aren't quite there yet. Having said that, if you've used these credentials to create your pool, then I assume that you have transferred funds to an **Account** address created from them. The balance of such address can be tracked directly in Jörmungandr via [Get Account State](https://input-output-hk.github.io/jormungandr/jcli/rest.html#get-account-state). 

Keep in mind however that:

- Such type of chimeric account (that aren't UTxO-based) will likely be discontinued in the MainNet era. They are being explored as part of the ITN, but I'd still recommend to stick with UTxO accounting when possible. 

- `cardano-wallet` only keeps track of UTxO-based addresses and, a single reward account that is part of the HD hierarchy and derived from the root seed. But there's no way to get back a seed from an existing reward account.

**Closed as completed by KtorZ** 2020-01-03 14:16 UTC
