### ISSUE TITLE
Wallet initialization using blockchain data fails with unique constraint failure and ErrPointAlreadyExists

### ISSUE THREAD

**Issue by hodlonaut** [cardano-foundation/cardano-wallet#1181] opened 2019-12-15 10:06 UTC
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: 6c6d1dc)  |
| Platform     | Mac OS           |
| Installation | source, `master` branch             |

Additional context: https://github.com/input-output-hk/jormungandr/issues/1366

# Steps to Reproduce

On startup, encountering the following:

```
[cardano-wallet.stake-pools:Info:24] [2019-12-15 09:59:33.63 UTC] Discovered stake pool registration: Registration of 03a01cb9 owned by [ed25519_pk120uk3rugx3fl2jrl2rfzmara6654klpywgwmwweu2n0z7mg7zc2s03jqsk,ed25519_pk120uk3rugx3fl2jrl2rfzmara6654klpywgwmwweu2n0z7mg7zc2s03jqsk]
[cardano-wallet.stake-pools:Info:24] [2019-12-15 09:59:33.63 UTC] Discovered stake pool registration: Registration of 999ba287 owned by [ed25519_pk14t0lqxjcrqfs9xjgw0g258cq2drrfkrxx4dh5zp6g46m5xcskgjsk36q7x]
SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: pool_owner.pool_id, pool_owner.pool_owner
[cardano-wallet.stake-pools:Error:24] [2019-12-15 09:59:33.63 UTC] Recoverable error following the chain: SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: pool_owner.pool_id, pool_owner.pool_owner
[cardano-wallet.stake-pools:Info:24] [2019-12-15 09:59:34.15 UTC] Applying blocks [0.530 ... 0.1603]
[cardano-wallet.stake-pools:Info:24] [2019-12-15 09:59:34.15 UTC] Writing stake-distribution for epoch 1
[cardano-wallet.stake-pools:Error:24] [2019-12-15 09:59:34.15 UTC] Failed to roll forward: ErrMonitorStakePoolsPoolAlreadyExists (ErrPointAlreadyExists (BlockHeader {slotId = SlotId {epochNumber = EpochNo {unEpochNo = 0}, slotNumber = SlotNo {unSlotNo = 530}}, blockHeight = Quantity {getQuantity = 1}, headerHash = Hash {getHash = "\215\159 \130\221\209*\184\129\247xo7n\225\220T\135t\239\164\130>\254\132\224(\253~r\198?"}, parentHeaderHash = Hash {getHash = "\142M*4?=\207\147&0\173\144&5\179\232\209h\230r\137\EOT&/,CJO\143\147N\199\182v"}}))
[cardano-wallet.stake-pools:Notice:24] [2019-12-15 09:59:34.15 UTC] Worker has exited: main action is over.
[cardano-wallet.api:Info:273] [2019-12-15 10:03:07.93 UTC] [RequestId 0] [GET] /v2/stake-pools
[cardano-wallet.api:Warning:273] [2019-12-15 10:03:07.94 UTC] [RequestId 0] 503 Service Unavailable in 0.009607s
```

## Expected behavior

- The server follows the chain without any issue and I can query the list of stake pools.

## Actual behavior
 

after this point in time attempt to access REST API errors results in:

```json
{"code":"not_synced","message":"I can't list stake pools yet because I need to scan the blockchain for metrics first. I'm at 44%"}
```

---

# Resolution 

- Allow storing multiple duplicate owners in the sqlite database ==> #1182 

---

# QA 

- Extended db properties to generate cases with duplicate pool owners and also added proper labelling.
 
```
    Stake Pool properties
      putPoolRegistration then readPoolRegistration yields expected result
        +++ OK, passed 100 tests.
      rollback of PoolRegistration
        +++ OK, passed 100 tests:
        88% rolled back some
        74% owner has many pools
      putPoolRegistration . listRegisteredPools yield pools
        +++ OK, passed 100 tests 
        59% same owner multiple time in the same certificate
```

Note: this db change is incompatible with current `master`, meaning that existing databases built with master have to be wiped-out. 

- Trying syncing with nightly with this fix, I can indeed sync with the network:

```
$ cardano-wallet network information
Ok.
{
    "network_tip": {
        "epoch_number": 1,
        "slot_number": 30494
    },
    "node_tip": {
        "height": {
            "quantity": 7261,
            "unit": "block"
        },
        "epoch_number": 1,
        "slot_number": 30494
    },
    "sync_progress": {
        "status": "ready"
    },
    "next_epoch": {
        "epoch_start_time": "2019-12-15T19:13:37Z",
        "epoch_number": 2
    }
}
```

- And I can see the pool with duplicate owners:

```
$ cardano-wallet stake-pools list 
Ok.
[
...
    {
        "metrics": {
            "controlled_stake": {
                "quantity": 0,
                "unit": "lovelace"
            },
            "produced_blocks": {
                "quantity": 0,
                "unit": "block"
            }
        },
        "cost": {
            "quantity": 0,
            "unit": "lovelace"
        },
        "margin": {
            "quantity": 2,
            "unit": "percent"
        },
        "apparent_performance": 0,
        "metadata": {
            "homepage": "https://sanstone.io",
            "owner": "ed25519_pk120uk3rugx3fl2jrl2rfzmara6654klpywgwmwweu2n0z7mg7zc2s03jqsk",
            "name": "Sandstone Stake Pool",
            "ticker": "SAND",
            "pledge_address": "addr1s4flj6y03q698a2g0agdyt050ht2jkmuy3epmdem832dutmdrctp2f556fv"
        },
        "id": "03a01cb9acffb3374c9a86ff39b2b5d85128c9ce3ac3fdba51ceceaca0685f98"
    },
...
]
```

- Also, peaking directly into the sqlite database:

```
sqlite> SELECT pool_owner_index, pool_owner FROM pool_owner WHERE pool_id LIKE "%03a01%";
0|ed25519_pk120uk3rugx3fl2jrl2rfzmara6654klpywgwmwweu2n0z7mg7zc2s03jqsk
1|ed25519_pk120uk3rugx3fl2jrl2rfzmara6654klpywgwmwweu2n0z7mg7zc2s03jqsk
```

The owners are correctly stored (and identical) but with different indexes. (this pool was known to have multiple times the same owner).

**Comment by KtorZ** [comment] 2019-12-15 10:59
Hey @hodlonaut, thanks for reporting this.
I noticed this recently, one of the pools registered on the testnet has two identical owners. I've raised the concern to Jormungandr's team who don't see any particular issue with this (see https://github.com/input-output-hk/jormungandr/issues/1366).

Therefore, we're going to have to slightly adjust our database interface to play nice with this.

**Comment by KtorZ** [comment] 2019-12-15 12:02
@hodlonaut I've updated your ticket to use our BUG template :+1:

**Comment by hodlonaut** [comment] 2019-12-15 12:12
Thanks @KtorZ !

**Comment by KtorZ** [comment] 2019-12-15 14:49
Okay, fix implemented, QA done. Merged into `master`.

**Closed as completed by KtorZ** 2019-12-15 14:49 UTC

**Comment by Fell-x27** [comment] 2020-04-01 09:28
The problem is still there. Looks like it happens after epoch changing. 
The error is "I can't list stake pools yet because I need to scan the blockchain blah blah blah"  and percent is static until restart the wallet. Then it starts to grow, but very slow. About 1$ per 2-3 mins.

**Comment by KtorZ** [comment] 2020-04-01 16:27
What version, what network please :) ?
