### ISSUE TITLE
(ADP-257) Change ByronMigration endpoints

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1658] opened 2020-05-13 08:55 UTC
# Context

As an API Client,
I want to be able to empty a wallet and send all funds to a list of addresses,
So that I can easily move funds around and have the wallet dealing with fees for me.

# Decision

We first add new migration endpoint that enables to transfer a given wallet to the addresses specified. The following cases are to be supported : 
(a) byron wallet -> shelley addresses
(b) byron wallet -> byron addresses
Moreover, MigrationWalletInfo is to be operative 

This is jormungandr context!

# Acceptance Criteria

1. New endpoints in ByronWallet are changed in all needed places in codebase (swagger, API endpoint).
2. Needed unit tests for types are added.
3. Implementation is added and integration tests work

---

# Development 

# QA 

1. We changed how Byron migration endpoints work. Now they accept source wallet id and reciepent addresses. This gave rise to many changes in our codebase, from swagger up to Wallet core-integration tests. Would be worth at this changes
2. Added integration tests for checking address cycling https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs#L1344
3. added a number of property tests for `assignMigrationAddresses` https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs#L92-L101

**Comment by Anviking** [comment] 2020-05-18 13:10
What is the reason to not also support "Shelley wallet -> Shelley addresses"?

**Comment by paweljakubas** [comment] 2020-05-18 13:18
Because in this task I am after refactoring ByronMigration. In the next task I will add address shelley -> shelley in a sense that the endpoints will be added to shelley transactions endpoint family

**Comment by piotr-iohk** [comment] 2020-05-21 15:04
Doing some exploratory testing and encountered this case on jormungandr. When trying to migrate to an address `DdzFFzCqrhtCNjPk5Lei7E1FxnoqMoAYtJ8VjAWbFmDb614nNBWBwv3kt6QHJa59cGezzf6piMWsbK7sWRB5sv325QqWdRuusMqqLdMt` I am getting `500`.

To reproduce:
1. Launch Jorm:
```
cd /lib/jormungandr/test/data/jormungandr/test_scripts
./wallet_launch
```
:point_down: 

2. Create byron wallet with funds:
```
arctic decade pink easy jar index base bright vast ocean hard pizza

curl  -vX POST http://localhost:8090/v2/byron-wallets/random \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"name": "Byron Faucet ",
"mnemonic_sentence": [ "arctic", "decade", "pink", "easy", "jar", "index", "base", "bright", "vast", "ocean", "hard", "pizza"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```

3. Try to migrate to address: `DdzFFzCqrhtCNjPk5Lei7E1FxnoqMoAYtJ8VjAWbFmDb614nNBWBwv3kt6QHJa59cGezzf6piMWsbK7sWRB5sv325QqWdRuusMqqLdMt`

```
curl -vX POST http://localhost:8090/v2/byron-wallets/aa129a07d1ce083e67597348f1788747a034686e/migrations \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"passphrase": "Secure Passphrase",
"addresses": ["DdzFFzCqrhtCNjPk5Lei7E1FxnoqMoAYtJ8VjAWbFmDb614nNBWBwv3kt6QHJa59cGezzf6piMWsbK7sWRB5sv325QqWdRuusMqqLdMt"]
}' --http1.1  |  jq
```

Result:

```
Code = 500,
Message = Something went wrong
```

In the log there is:
```
[POST] /v2/byron-wallets/aa129a07d1ce083e67597348f1788747a034686e/migrations
ErrUnexpectedNetworkFailure (Link {_segments = ["api","v0","message"], _queryParams = []}) (FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = "127.0.0.1", baseUrlPort = 8080, baseUrlPath = ""},"/api/v0/message"), requestQueryString = fromList [], requestBody = Just ((),application/octet-stream), requestAccept = fromList [], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = "POST"} (Response {responseStatusCode = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseHeaders = fromList [("content-type","text/plain; charset=utf-8"),("content-length","54"),("date","Thu, 21 May 2020 15:01:27 GMT")], responseHttpVersion = HTTP/1.1, responseBody = "Internal server error: Structure invalid: transaction\n"}))

```

**Comment by piotr-iohk** [comment] 2020-05-22 13:33
Added scenario to illustrate :point_up_2:  in https://github.com/input-output-hk/cardano-wallet/pull/1682.

**Comment by piotr-iohk** [comment] 2020-05-22 15:32
Closing, there is still https://github.com/input-output-hk/cardano-wallet/issues/1675 in progress.

**Closed as completed by piotr-iohk** 2020-05-22 15:32 UTC
Labels: Feature
